# Utility and productivity services
services:
  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    profiles: ["utilities", "database", "all"]
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PWD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${CONTAINERS_PATH}/mariadb:/config
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping"]
      start_period: 5s
      timeout: 5s
    restart: always

  projectsend:
    image: linuxserver/projectsend
    container_name: projectsend
    profiles: ["utilities", "file-sharing", "all"]
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
    volumes:
      - ${CONTAINERS_PATH}/projectsend/config:/config
      - ${CONTAINERS_PATH}/projectsend/data:/data
    ports:
      - 8083:80
    healthcheck:
      test: ["CMD", "curl", "-ILXGET", "http://localhost"]
    restart: always

  syncthing:
    image: linuxserver/syncthing
    container_name: syncthing
    profiles: ["utilities", "sync", "all"]
    network_mode: host
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
    volumes:
      - ${CONTAINERS_PATH}/syncthing:/config
      - ${SYNCTHING_PATH}:/targets
    healthcheck:
      test: ["CMD", "curl", "-ILXGET", "http://localhost:8384"]
    restart: always

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    profiles: ["utilities", "passwords", "all"]
    environment:
      ADMIN_TOKEN: ${VAULT_TOKEN}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONTAINERS_PATH}/vaultwarden:/data
    ports:
      - 8084:80
    healthcheck:
      test: ["CMD", "curl", "-ILXGET", "http://localhost"]
    restart: always
